# Generated by Django 3.2.8 on 2021-10-08 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=300)),
                ('location', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=False)),
                ('time_created', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
