# Generated by Django 3.2.7 on 2021-10-10 01:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0001_initial'),
        ('tags', '0002_eventtags_usertags'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EventTags',
            new_name='EventTag',
        ),
        migrations.RenameModel(
            old_name='UserTags',
            new_name='UserTag',
        ),
    ]
